In [4]:
# Accessing or changing specific elements,rows,columns etc.

import numpy as np

a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [123]:
# Get a specific element (r,c)

# to get 9 from an array
a[1,3] #the indexing will start from 0 just like in lists

9

In [135]:
# Get a specific row or column

# to get the 2nd row and the 4th column
print(a[1,:])
print(a[:,3])

[ 6  7 21  9 10]
[4 9]


In [20]:
# Get the elements and also using the concept of stepsize [start:end:stepsize]

# get the [1,3,5] elements

print(a[0,0:5:2]) #starting from 1 so 0th index ending at 5 so we'll take (index of 5)+1 and a stepsize of 2 as we want to alternate
print(a[0, 0:-1:2]) # we can also do negative indexing

[1 3 5]
[1 3]


In [47]:
# to change elements in an array

a[0,4] = 69
print(a)

# can change an entire row or column as well
a[:,2] = [5,21]
print(a) #these changes are permanent

[[ 1  2  5  4 69]
 [ 6  7 21  9 10]]
[[ 1  2  5  4 69]
 [ 6  7 21  9 10]]


In [87]:
# 3d example

b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b) 

# get a specific element, for example -> 6 and 3
print(b[1,0,1])
print(b[0,1,0])

# get a row or column, for example -> [3,4] and [5,7]
print(b[0,1,:])
print(b[1,:,0])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
6
3
[3 4]
[5 7]


In [93]:
# replacing arrays

# replace [[1,2],[3,4]]
b[0,:,:] = [[9,7],[5,3]]
print(b)

[[[9 7]
  [5 3]]

 [[5 6]
  [7 8]]]
