In [22]:
import numpy as np

# all 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
# all 1s matrix
np.ones((2,4,3), dtype='int32')

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [42]:
# any other number
np.full((2,5), 69, dtype = 'float16')

array([[69., 69., 69., 69., 69.],
       [69., 69., 69., 69., 69.]], dtype=float16)

In [58]:
# full_like method --> allows us to use an already built array
z = np.array([[1,2,3,4,5],[6,7,8,9,10]])


print(np.full_like(z,88))
# or we could do
print(np.full(z.shape,78))

[[88 88 88 88 88]
 [88 88 88 88 88]]
[[78 78 78 78 78]
 [78 78 78 78 78]]


In [70]:
# Random decimal numbers

print(np.random.rand(4,2))

# OR

print('\n')

print(np.random.random_sample(z.shape))

[[0.90474988 0.11192109]
 [0.16926732 0.87647558]
 [0.89432089 0.37345074]
 [0.37141963 0.5053858 ]]


[[0.64432577 0.07292218 0.17618793 0.75815763 0.63361817]
 [0.20867355 0.3242868  0.68830588 0.61743273 0.67438728]]


In [110]:
# Random Integer values

# for this we have to mention the start value(inclusive) and end value(exclusive), are the no.s jinke beech mei array k element no.s exist karenge
# and also mention the size of array

print(np.random.randint(2,6, size=(3,3)))
print('\n')
print(np.random.randint(-6,5, size=(4,3,2)))

[[3 5 5]
 [2 2 3]
 [5 5 3]]


[[[-1  4]
  [ 0 -4]
  [-1 -3]]

 [[ 4  3]
  [-6  0]
  [-4 -2]]

 [[-1  2]
  [ 1 -1]
  [-4  3]]

 [[ 0 -2]
  [-4 -3]
  [-5  4]]]


In [116]:
# identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
import numpy as np
# repeating elements in an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,5,axis=0) #(kisko repeat karna h, kitni times repeat karna hai, and konsi axis pe repeat karna hai)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [142]:
# problem 
output = np.ones((5,5),dtype = 'int32')
print(output)

z = np.zeros((3,3),dtype = 'int32')
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 9 0]
 [0 0 0]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [148]:
 # for making the copy of an array
w = np.array([1,2,3])
x = w.copy()
x[0] = 69
print(x)
print(w)
#using the .copy keyword does not change the original array but aliasing the arrays, it would have manipulated the og array


[69  2  3]
[1 2 3]
