#### LOAD DATA FROM FILE

In [ ]:
import numpy as np
filedata = np.genfromtxt('NumPy/data.txt', delimiter=',') #delimeter acts as the sperator btw the elements
filedata.astype('int32') #this makes a copy of actual filedata as the og is in float 
# if we want to change the actual file we can just do
filedata = filedata.astype('int32')

#### Boolean Masking and Advanced Indexing

In [ ]:
# we can find how many values are greater than or an operation than 50 in filedata by

filedata > 50

# we can also use operators for multiple cases
((filedata>50) & (filedata<100))
# OR
(~(filedata>50) & (filedata<100))

# we can also extract the values in an array by indexing
filedata[filedata>69]

In [28]:
# we can index with a list in NumPy 
# for example we want 2,6,9 from a list

a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,3,-1]]

array([2, 4, 9])

In [ ]:
# we can find out if any values in filedata were >50 
np.any(filedata > 50, axis=0)

In [68]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
print(a,'\n')

# print[[11 12]
    # [16 17]] 
print(a[2:4,0:2],'\n')


# print[ 2  8 14 20] 
print(a[[0,1,2,3],[1,2,3,4]],'\n')

# print[[ 4  5]
      #[24 25]
     #[29 30]]

b=a[4:6,3:5]
c=a[0,3:5]
print(np.vstack((c,b)),'\n') 

# or we can do
print(a[[0,4,5],3:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]] 

[[11 12]
 [16 17]] 

[ 2  8 14 20] 

[[ 4  5]
 [24 25]
 [29 30]] 

[[ 4  5]
 [24 25]
 [29 30]]
