In [2]:
import numpy as np

In [4]:
a = np.array([1,2,3,4,5])
print(a) #1d array

[1 2 3 4 5]


In [6]:
b = np.array([[3.2,1.5,6.9],[8.7,4.1,7.3]])
print(b) #2d array

[[3.2 1.5 6.9]
 [8.7 4.1 7.3]]


In [12]:
# Get Dimension
print(a.ndim)
print(b.ndim)

1
2


In [16]:
# Get Shape --> tells us the no. of rows and columns 
print(a.shape)
print(b.shape)

(5,)
(2, 3)


In [22]:
# Get Type --> tells us the data type of the array, by default it is 'int32'
print(a.dtype) #by default dtype will be int 32 in a
c = np.array([1,2,3], dtype='int16')
print(c.dtype)

int32
int16


In [30]:
# Get size --> gives us how many bytes it will take as int32 take 4 bytes and int 16 take 2 byte
print(a.itemsize)
print(b.itemsize)
print(c.itemsize) 

4
8
2


In [40]:
# get total size
print(a.size) # .size tells us the total no. of elements in array
print(b.size)

# for the total size we can multiply .size and .itemsize or use .nbbytes
print(a.size*a.itemsize)
print(a.nbytes)

print(b.nbytes)

5
6
20
20
48


In [100]:
a = np.array([1,2,3,4,5,6])
print(a)
print("The dimension of a is",a.ndim)
print("The no. of rows and columns in a are",a.shape)
print("The data type of a is",a.dtype)
print(f"a take almost {a.itemsize} bytes")
print("Total size is",a.nbytes)

[1 2 3 4 5 6]
The dimension of a is 1
The no. of rows and columns in a are (6,)
The data type of a is int32
a take almost 4 bytes
Total size is 24


In [98]:
c = np.array([[[1,2],[3,4],[5,6]]], dtype='int16')
print(c)
print("The dimension of c is",c.ndim)
print("The no. of rows and columns in c are ",c.shape)
print("The data type is",c.dtype)
print(f"c takes almost {c.itemsize} bytes")
print("Total size is ",c.size*c.itemsize)

[[[1 2]
  [3 4]
  [5 6]]]
The dimension of c is 3
The no. of rows and columns in c are  (1, 3, 2)
The data type is int16
c takes almost 2 bytes
Total size is  12


In [104]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,0,6,3]], dtype = 'int8')
print(b)
print("The dimension of b is",b.ndim)
print("The no. of rows and columns in b are",c.shape)
print("The data type is",b.dtype)
print(f"b takes almost {b.itemsize} byte")
print("Total size is",b.size*b.itemsize)

[[1 2 3 4]
 [5 6 7 8]
 [9 0 6 3]]
The dimension of b is 2
The no. of rows and columns in b are (1, 3, 2)
The data type is int8
b takes almost 1 byte
Total size is 12
