In [2]:
import numpy as np

a = np.array([1,2,3,4])

print(a+2)
print(a-2)
print(a*2)
print(a/2)
print(a**2)

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]


In [4]:
b = np.array([6,7,8,9])
print(a+b)

[ 7  9 11 13]


In [10]:
# Take sine or cosine of array
print(np.sin(a))
print(np.cos(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


#### Linear Algebra

In [17]:
a = np.ones((2,3))
print(a)
b = np.zeros((3,2))
print(b)
# we can not normally multiply the two arrays therefore we'll have to use 
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


array([[0., 0.],
       [0., 0.]])

In [19]:
# to find the determinant of matrix
c = np.identity(3)
np.linalg.det(c)

1.0

#### Statistics

In [8]:
import numpy as np

stats = np.array([[1,2,3,4],[9,8,7,6]])
print(stats)

[[1 2 3 4]
 [9 8 7 6]]


In [22]:
print(np.max(stats))
print(np.max(stats,axis=0))
print(np.max(stats,axis=1))
print(np.min(stats))
print(np.min(stats,axis=0))
print(np.min(stats,axis=1))

9
[9 8 7 6]
[4 9]
1
[1 2 3 4]
[1 6]


In [24]:
np.sum(stats)

40

In [56]:
z = np.full((2,3),69)
x = np.full((3,2),31)
print(np.matmul(z,x))

[[6417 6417]
 [6417 6417]]


1.0
31
69
