In [28]:
import numpy as np

# Create a 1D NumPy array with numbers from 1 to 10.
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a,'\n')

# Create a 3x3 NumPy array filled with zeros.
b = np.zeros((3,3))
print(b,'\n')

# Create a 4x4 identity matrix using NumPy.
c = np.identity(4)
print(c,'\n')

# Convert a Python list [1, 2, 3, 4] into a NumPy array.
list1 = [1,2,3,4]
array1 = np.array(list1)
print(array1,'\n')

# Create a 2D array of shape (3, 4) with random integers between 10 and 50.
d = np.random.randint(10,50, size=(3,4))
print(d)

[ 1  2  3  4  5  6  7  8  9 10] 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

[1 2 3 4] 

[[10 33 11 10]
 [15 27 34 44]
 [38 14 17 43]]


In [30]:
# Extract the last two rows of the following array
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
print(arr[1:3,:])

[[4 5 6]
 [7 8 9]]


In [62]:
# Replace the second column of the following array with all ones:
arr1 = np.array([[10, 20, 30], 
                [40, 50, 60], 
                [70, 80, 90]])
arr1[:,1] = 1
print(arr1)

[[10  1 30]
 [40  1 60]
 [70  1 90]]


In [72]:
# Reverse the rows and columns of a 2D array.
arr1[::-1]

array([[70,  1, 90],
       [40,  1, 60],
       [10,  1, 30]])

In [84]:
# Add two 1D arrays of shape (5,) element-wise.
a = np.full((5,),45)
print(a)
b = np.random.randint(1,100,size=(5,))
print(b)
print(a+b)

[45 45 45 45 45]
[32 98 61 47 22]
[ 77 143 106  92  67]


In [90]:
# Multiply two 2D arrays of shape (3, 3) using both element-wise multiplication and matrix multiplication.
c = np.random.randint(1,100,size=(3,3))
d = np.random.randint(1,100,size=(3,3))
print(c*d)
print(np.matmul(c,d))

[[4050 2300 1380]
 [ 396 4600 4620]
 [ 438 2752 1872]]
[[ 5088  5559  7494]
 [ 4098  8923 12846]
 [ 7866  7590 10092]]


In [98]:
z = np.array([1,2,3,4,5,6,7,8,9,10])
print("MEAN: ",np.mean(z))
print('MEDIAN:',np.median(z))
print('STANDARD DEVIATION:',np.std(z))

MEAN:  5.5
MEDIAN: 5.5
STANDARD DEVIATION: 2.8722813232690143


In [118]:
# Reshape a 1D array of size 12 into a 3x4 2D array.
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
y = x.reshape((3,4))
print(y)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [132]:
# Flatten a 2D array into a 1D array.
before = np.random.randint(1,100,size=(2,3))
after = before.reshape((6,))
print(after)

[47 72 25 64 33 75]


In [144]:
# Create a 2D array of shape (3, 3) and add 5 to each element.
a = np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
print(a+5,'\n')

# Multiply a 2D array of shape (4, 3) by a 1D array of shape (3,).
b = np.array([[1,2,3],
             [5,6,7],
             [8,9,0],
             [4,2,9]])
c = np.array([[9,],
            [7,],
            [3]])
print(np.matmul(b,c))

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]] 

[[ 32]
 [108]
 [135]
 [ 77]]


In [148]:
# Create an array of integers from 1 to 20. Extract only the even numbers using Boolean indexing.
w = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(w[1:20:2])

[ 2  4  6  8 10 12 14 16 18 20]


In [150]:
# Replace all negative numbers in the array [-1, 2, -3, 4, -5] with zero.
array = np.array([-1,2,-3,4,-5])
array[array<0] = 0
print(array)

[0 2 0 4 0]


In [154]:
# Create a 5x5 array with random numbers. Normalize the array so all values are between 0 and 1.
ar = np.random.randint(0,2,size=(5,5))
print(ar)

[[1 1 1 1 0]
 [1 0 1 1 1]
 [1 1 0 1 0]
 [1 1 0 0 1]
 [1 1 0 1 0]]


In [162]:
# Find the eigenvalues and eigenvectors of a 2x2 matrix.
mat = np.array([[4,-2],
               [1,1]])

eigenvalues, eigenvectors = np.linalg.eig(mat)
print("eigenvalues: ",eigenvalues)
print("eigenvectors: \n",eigenvectors)

eigenvalues:  [3. 2.]
eigenvectors: 
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]
