In [14]:
import numpy as np

before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

# we can change the shape of array but it should be same no. of elements like (2,4)->(4,2) or (8,1) or (2,2,2) but not (2,3) or (3,4)

after = before.reshape((8,1))
print(after)

after1 = before.reshape((2,2,2))
print(after1)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [32]:
# Vertically stacking vectors

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

# Vertically stacking can be used to form arrays but stacking on top of each other but also they should be of same shape

print(np.vstack((a,b,a,b))) 

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [44]:
# Horizontally stacking vectors
# Similar to vstack

c = np.zeros((2,4))
d = np.ones((2,2))

np.hstack((c,d,c,d))

array([[0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1.]])